[package]
name = "my_tiny_http"
version = "0.1.0"
edition = "2021"

[features]
default = ["log"]
#default = ["log", "ssl-openssl"]
ssl = ["ssl-openssl"]
ssl-openssl = ["openssl", "zeroize"]
ssl-rustls = ["rustls", "rustls-pemfile", "zeroize"]
ssl-native-tls = ["native-tls", "zeroize"]

[dependencies]
ascii = "1.0"
chunked_transfer = "1"
httpdate = "1.0.2"

log = { version = "0.4.4", optional = true }
native-tls = { version = "0.2", optional = true }
openssl = { version = "0.10", optional = true }
rustls = { version = "0.20", optional = true }
rustls-pemfile = { version = "0.2.1", optional = true }
zeroize = { version = "1", optional = true }